### ISSUE TITLE
Error while running "make"

### ISSUE THREAD

**Issue by alxhotel** [mgp25/curve25519-php#5]
This is what I got:

```
/var/www/gecko/curve25519-php/curve.c: In function 'zif_curve25519_sign':
/var/www/gecko/curve25519-php/curve.c:37:40: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
   RETURN_STRINGL((char*)signature, 64,1);
                                        ^
/var/www/gecko/curve25519-php/curve.c:37:3: error: 'RETURN_STRINGL' undeclared (first use in this function)
   RETURN_STRINGL((char*)signature, 64,1);
   ^
/var/www/gecko/curve25519-php/curve.c:37:3: note: each undeclared identifier is reported only once for each function it appears in
/var/www/gecko/curve25519-php/curve.c: In function 'zif_curve25519_private':
/var/www/gecko/curve25519-php/curve.c:76:33: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
     RETURN_STRINGL(random, 32, 1);
                                 ^
/var/www/gecko/curve25519-php/curve.c:76:5: error: 'RETURN_STRINGL' undeclared (first use in this function)
     RETURN_STRINGL(random, 32, 1);
     ^
/var/www/gecko/curve25519-php/curve.c: In function 'zif_curve25519_public':
/var/www/gecko/curve25519-php/curve.c:97:37: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL((char*)public, 32, 1);
                                     ^
/var/www/gecko/curve25519-php/curve.c:97:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL((char*)public, 32, 1);
  ^
/var/www/gecko/curve25519-php/curve.c: In function 'zif_curve25519_shared':
/var/www/gecko/curve25519-php/curve.c:124:34: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(shared_key, 32, 1);
                                  ^
/var/www/gecko/curve25519-php/curve.c:124:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL(shared_key, 32, 1);
  ^
make: *** [curve.lo] Error 1
```

I did installed PHP 7.

Any ideas ?

**Comment by mgp25** [comment]
I havent test it in PHP7, use PHP5.6, ill check for PHP7 support soon. Let me know if that worked

**Comment by alxhotel** [comment]
Yep. Downgrading to PHP 5.6 solved it.

So there is a compatibility issue that needs to be fix...

**Comment by mgp25** [comment]
It was prepared to work with PHP5.6 not PHP7, ill add PHP7 support when i have more time

Happy xmas

Regards
