### ISSUE TITLE
Error in command make

### ISSUE THREAD

**Issue by emontoro** [mgp25/curve25519-php#6]
My php is 5.3.3
S.O CentOs 64 bits

I hope you can help me

regards

/bin/sh /opt/curve25519-php-master/libtool --mode=compile cc  -I. -I/opt/curve25519-php-master -DPHP_ATOM_INC -I/opt/curve25519-php-master/include -I/opt/curve25519-php-master/main -I/opt/curve25519-php-master -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/curve25519-php-master/curve.c -o curve.lo
libtool: compile:  cc -I. -I/opt/curve25519-php-master -DPHP_ATOM_INC -I/opt/curve25519-php-master/include -I/opt/curve25519-php-master/main -I/opt/curve25519-php-master -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/curve25519-php-master/curve.c  -fPIC -DPIC -o .libs/curve.o
/opt/curve25519-php-master/curve.c:158: error: ‘PHP_FE_END’ undeclared here (not in a function)
make: **\* [curve.lo] Error 1

**Comment by mgp25** [comment]
This was prepared to be compiles with PHP 5.6 please read before opening a new issue

Regards
